# 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'field.jpg',
    'clay_plate.png',
    'canoe.png',
    'aiming_point.png',
    'hudle_1.png',
    'hudle_2.png',
    'hudle_3.png',
    'river.jpg',
    'rock.png',
    'title.png',
    'track.png',
    'track_finish_line.png',
    'tuk_credit.png',
    'yoshi.png'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [

]

